# 华鼎模板默认值
huading_template:
  defaults:
    出库类型: "201"              # 销售出库
    配送方式: "共配"
    指定库存状态: "正常"
    是否垫付: "否"
    加急程度: 0                  # 0=普通
    是否制定批次: "否"
    业务类型: ""
    业务模式: ""
    门店三方编码: ""
    商品三方SPEC编号: ""
    指定车型（专配）: ""
    付款方式: ""
    快递公司: ""
    单价: ""
    总金额: ""
    批次号: ""
    生产日期: ""
    生产厂家编号: ""
    门店收货地址编码: ""
    C端快递公司: ""
